import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Palmer Penguins: Initial Static Exploratory Data Analysis\n",
    "\n",
    "This notebook contains the static visualization prototypes referenced in the report. Before migrating to the Plotly and Streamlit-driven interactive dashboard (`app.py`), the initial workflow relied on static plots generated by `seaborn` and `matplotlib`.\n",
    "\n",
    "These early iterations made it difficult to dynamically filter across islands/species or simultaneously observe ML clusters and physical distributions."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.cluster import KMeans\n",
    "\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# 1. Load Data\n",
    "df = sns.load_dataset('penguins')\n",
    "df = df.dropna(subset=['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g', 'sex'])\n",
    "df['bill_ratio'] = df['bill_length_mm'] / df['bill_depth_mm']\n",
    "\n",
    "# Define global color palette for static plots\n",
    "species_palette = {'Adelie': '#7F3C8D', 'Chinstrap': '#11A579', 'Gentoo': '#3969AC'}\n",
    "\n",
    "sns.set_theme(style=\"whitegrid\")\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Static Distributions and Relationships\n",
    "Static plots representing body mass distribution and the relationship between flipper length and body mass."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.figure(figsize=(10, 6))\n",
    "sns.histplot(data=df, x='body_mass_g', hue='species', element='step', palette=species_palette)\n",
    "plt.title('Body Mass Distribution by Species')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.figure(figsize=(10, 6))\n",
    "sns.scatterplot(data=df, x='flipper_length_mm', y='body_mass_g', hue='species', \n",
    "                size='bill_ratio', sizes=(20, 200), alpha=0.7, palette=species_palette)\n",
    "plt.title('Flipper Length vs Body Mass')\n",
    "plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Static Machine Learning View (PCA & K-Means)\n",
    "A static rendering of the Principal Component Analysis and K-Means clusters."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Preprocessing for ML\n",
    "features = ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']\n",
    "X_scaled = StandardScaler().fit_transform(df[features])\n",
    "\n",
    "# K-Means\n",
    "kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)\n",
    "df['ml_cluster'] = kmeans.fit_predict(X_scaled).astype(str)\n",
    "\n",
    "# PCA for 2D visualization\n",
    "pca = PCA(n_components=2)\n",
    "pca_res = pca.fit_transform(X_scaled)\n",
    "df['pca_1'] = pca_res[:, 0]\n",
    "df['pca_2'] = pca_res[:, 1]\n",
    "\n",
    "plt.figure(figsize=(10, 6))\n",
    "sns.scatterplot(data=df, x='pca_1', y='pca_2', hue='ml_cluster', style='species', \n",
    "                palette='Dark2', s=100, alpha=0.8)\n",
    "plt.title('Static PCA & K-Means Clustering')\n",
    "plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("static_visualizations.ipynb", "w", encoding='utf-8') as f:
    json.dump(notebook, f, indent=1)
